// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDfiEVxe5x2gpT9-Zu8qxEQJQJohiYIGc',
    appId: '1:605763614155:web:13e88ad2a88f60c975724e',
    messagingSenderId: '605763614155',
    projectId: 'hackathon-a6fe2',
    authDomain: 'hackathon-a6fe2.firebaseapp.com',
    storageBucket: 'hackathon-a6fe2.appspot.com',
    measurementId: 'G-LYFEWY3P6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc_jE2fRmdHqgkm7XkhbSrDFZHYir9yjA',
    appId: '1:605763614155:android:d7a67e73c4c24f3475724e',
    messagingSenderId: '605763614155',
    projectId: 'hackathon-a6fe2',
    storageBucket: 'hackathon-a6fe2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXRSiCBdZOPeNW_30XEeHWUqJpRvXvi1Y',
    appId: '1:605763614155:ios:01f73c84965e0b8c75724e',
    messagingSenderId: '605763614155',
    projectId: 'hackathon-a6fe2',
    storageBucket: 'hackathon-a6fe2.appspot.com',
    iosClientId: '605763614155-ft0uhgbe86247il8f2jrbfep1frpec68.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathonAssign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXRSiCBdZOPeNW_30XEeHWUqJpRvXvi1Y',
    appId: '1:605763614155:ios:baa0c90e1f6a21e575724e',
    messagingSenderId: '605763614155',
    projectId: 'hackathon-a6fe2',
    storageBucket: 'hackathon-a6fe2.appspot.com',
    iosClientId: '605763614155-c25pa3b20k3ciqn97urck42gnl5ribgv.apps.googleusercontent.com',
    iosBundleId: 'com.example.hackathonAssign.RunnerTests',
  );
}
